version: "3.3"

services:
    db:
        image: mariadb:10.6
        volumes:
            - data-mysql:/var/lib/mysql
            - ./initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
            timeout: 20s
            retries: 10

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - "8010:80"
        environment:
            - PMA_HOST=db:3306

    registry_webserver:
        depends_on:
            - db
        image: dronedb/registry:latest
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:5000/quickhealth" ]
            interval: 30s
            timeout: 10s
            retries: 5
        environment:
            - INSTANCE_TYPE=2
        tmpfs:
            - /tmp
        volumes:
            - ./data:/data
            - ./appsettings.json:/data/appsettings.json
        ports:
            - "5000:5000"
        restart: unless-stopped

    registry_node_1:
        depends_on:
            - registry_webserver
        image: dronedb/registry:latest
        environment:
            - INSTANCE_TYPE=1
        tmpfs:
            - /tmp
        volumes:
            - ./data:/data
            - ./appsettings.json:/data/appsettings.json
        restart: unless-stopped

    registry_node_2:
        depends_on:
            - registry_webserver
        image: dronedb/registry:latest
        environment:
            - INSTANCE_TYPE=1
        tmpfs:
            - /tmp
        volumes:
            - ./data:/data
            - ./appsettings.json:/data/appsettings.json
        restart: unless-stopped

volumes:
  data-mysql:
    driver: local