CREATE USER 'registry'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT USAGE ON *.* TO 'registry'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE `RegistryData` /*!40100 COLLATE 'latin1_general_ci' */;
CREATE DATABASE `RegistryAuth` /*!40100 COLLATE 'latin1_general_ci' */;
CREATE DATABASE `RegistryHangfire` /*!40100 COLLATE 'latin1_general_ci' */;

GRANT 
    EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES 
    ON `RegistryAuth`.* TO 'registry'@'%' WITH GRANT OPTION;
GRANT 
    EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES 
    ON `RegistryData`.* TO 'registry'@'%' WITH GRANT OPTION;
GRANT 
    EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES 
    ON `RegistryHangfire`.* TO 'registry'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
