// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registry.Web.Data;

#nullable disable

namespace Registry.Web.Data.MySqlMigrations.Migrations
{
    [DbContext(typeof(RegistryContext))]
    [Migration("20250929095516_AddPathBackToJobIndex")]
    partial class AddPathBackToJobIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Registry.Web.Data.Models.Batch", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Token");

                    b.HasIndex("DatasetId");

                    b.HasIndex("Start");

                    b.HasIndex("Status");

                    b.HasIndex("UserName", "Status");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileTypes")
                        .HasColumnType("longtext");

                    b.Property<Guid>("InternalRef")
                        .HasColumnType("char(36)");

                    b.Property<string>("OrganizationSlug")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreationDate");

                    b.HasIndex("InternalRef");

                    b.HasIndex("OrganizationSlug");

                    b.HasIndex("Slug");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BatchToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchToken");

                    b.ToTable("Entry");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.JobIndex", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DsSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hash")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime?>("LastStateChangeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MethodDisplay")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("OrgSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessingAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Queue")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SucceededAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("OrgSlug", "DsSlug");

                    b.HasIndex("OrgSlug", "DsSlug", "Hash");

                    b.ToTable("JobIndices");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.Organization", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Slug");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Slug");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.OrganizationUser", b =>
                {
                    b.Property<string>("OrganizationSlug")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("OrganizationSlug", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationsUsers");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.Batch", b =>
                {
                    b.HasOne("Registry.Web.Data.Models.Dataset", "Dataset")
                        .WithMany("Batches")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.Dataset", b =>
                {
                    b.HasOne("Registry.Web.Data.Models.Organization", "Organization")
                        .WithMany("Datasets")
                        .HasForeignKey("OrganizationSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.Entry", b =>
                {
                    b.HasOne("Registry.Web.Data.Models.Batch", "Batch")
                        .WithMany("Entries")
                        .HasForeignKey("BatchToken")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.OrganizationUser", b =>
                {
                    b.HasOne("Registry.Web.Data.Models.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.Batch", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.Dataset", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Registry.Web.Data.Models.Organization", b =>
                {
                    b.Navigation("Datasets");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
