name: Build and Publish Docker Image

on:
  push:
    branches:
    - master
    pull_request:
    - master
    tags:
    - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: |        
        git submodule update --force --recursive --init --remote
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: dronedb/registry
        tag-semver: |
          v{{version}}
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ steps.docker_meta.outputs.tags }}
          dronedb/registry:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}